name: Generate and Train Model

on:
  workflow_dispatch: # run manually
  push:
    paths:
      - "backend/train_model.py"
      - ".github/workflows/generate-model.yml"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Set up Kaggle credentials
        run: |
          mkdir -p ~/.kaggle
          echo "{\"username\":\"$KAGGLE_USERNAME\",\"key\":\"$KAGGLE_KEY\"}" > ~/.kaggle/kaggle.json
          chmod 600 ~/.kaggle/kaggle.json
        env:
          KAGGLE_USERNAME: ${{ secrets.KAGGLE_USERNAME }}
          KAGGLE_KEY: ${{ secrets.KAGGLE_KEY }}

      - name: Download dataset from Kaggle
        run: |
          kaggle datasets download -d clmentbisaillon/fake-and-real-news-dataset -p data --unzip

      - name: Train model
        run: python backend/train_model.py

      - name: Commit and push model artifacts
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "github-actions"
          git pull --rebase
          git add backend/model.joblib backend/vectorizer.joblib
          git commit -m "Update trained model" || echo "No changes to commit"
          git push
