name: Generate Model

on:
  workflow_dispatch:   # run manually from Actions tab

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Setup Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      # 3. Install dependencies directly (no requirements.txt needed)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install scikit-learn pandas numpy joblib

      # 4. Run training script
      - name: Train model
        run: |
          python backend/train_model.py

      # 5. Upload trained artifacts
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: trained-model
          path: |
            backend/model.joblib
            backend/vectorizer.joblib
