name: Generate Model

on:
  workflow_dispatch:   # run manually

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Setup Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      # 3. Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install scikit-learn pandas numpy joblib kaggle

      # 4. Setup Kaggle
      - name: Setup Kaggle
        run: |
          mkdir -p ~/.kaggle
          echo '{"username":"${{ secrets.KAGGLE_USERNAME }}","key":"${{ secrets.KAGGLE_KEY }}"}' > ~/.kaggle/kaggle.json
          chmod 600 ~/.kaggle/kaggle.json

      # 5. Download dataset
      - name: Download dataset
        run: |
          mkdir -p data
          kaggle datasets download -d clmentbisaillon/fake-and-real-news-dataset -p data --unzip

      # 6. Train model
      - name: Train model
        run: |
          python backend/train_model.py

      # 7. Upload artifacts
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: trained-model
          path: |
            backend/model.joblib
            backend/vectorizer.joblib
