name: Generate and Upload Fake News Model

on:
  workflow_dispatch:   # You trigger manually from GitHub Actions tab
  push:
    paths:
      - "backend/train_model.py"
      - ".github/workflows/generate-model.yml"

jobs:
  build-model:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      # 3. Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4. Ensure backend folder exists
      - name: Create backend folder if missing
        run: mkdir -p backend

      # 5. Run training script
      - name: Train model
        run: python backend/train_model.py

      # 6. Upload trained artifacts (model + vectorizer)
      - name: Upload trained model
        uses: actions/upload-artifact@v4
        with:
          name: fake-news-model
          path: backend/*.joblib
          retention-days: 7
