name: Generate Model

on:
  workflow_dispatch:   # You trigger it manually from Actions tab

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      # 3. Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4. Train model
      - name: Train model
        run: |
          python backend/train_model.py

      # 5. Commit and push model
      - name: Commit and push model
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git fetch origin main
          git checkout main
          git add backend/model.joblib backend/vectorizer.joblib
          git commit -m "Update trained model" || echo "No changes to commit"
          git push origin main --force
