name: Generate Model

on:
  workflow_dispatch:   # Run manually from Actions tab

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Setup Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      # 3. Install dependencies (no requirements.txt needed)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install scikit-learn pandas numpy joblib flask gunicorn kaggle

      # 4. Train model (fetch dataset + train)
      - name: Train model
        run: |
          python backend/train_model.py

      # 5. Commit and push trained model
      - name: Commit and push model
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add backend/model.joblib backend/vectorizer.joblib || true
          git commit -m "Update trained model" || echo "No changes to commit"
          git push origin HEAD:main --force
